# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# NOTE: we build the container image first, and then we log in and push the container image;
#       this is intentional, as it still allows us maximum flexibility when building the
#       container image (vs. "buildAndPush") and it also allows us to diagnose image build
#       issues separately from container registry connection or push issues.

trigger:
- previewsignup

pool:
  vmImage: 'ubuntu-24.04' 

variables:
- group: 'github-access'
- name: 'containerRegistry'
  value: 'acr-morphic'
- name: 'repository'
  value: 'learnandtry-webapp'
- name: 'tag'
  value: '$(Build.BuildNumber)'

stages:
- stage: Docker
  displayName: Build and push Docker image
  jobs:
  - job: DockerBuildAndPush
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        containerRegistry: $(containerRegistry)
        dockerfile: './Dockerfile'
        repository: $(repository)
        tags: $(tag)
    - task: Docker@2
      displayName: Log in to container registry
      inputs:
        command: login
        containerRegistry: $(containerRegistry)
    - task: Docker@2
      displayName: Push docker image
      inputs:
        command: push
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        tags: $(tag)
    - task: Docker@2
      displayName: Log out of container registry
      inputs:
        command: logout
        containerRegistry: $(containerRegistry)
